name: CI

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses

          sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
          build-essential \
          git \
          zip \
          unzip \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          pkg-config

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install "cython<3.0"
          pip install buildozer virtualenv

      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << EOF
          [app]
          title = BlackFoxy AI
          package.name = blackfoxy
          package.domain = org.foxy
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 1.0

          requirements = python3,kivy==2.3.0,kivymd==1.2.0,pillow

          orientation = portrait
          fullscreen = 1

          android.api = 33
          android.minapi = 24
          android.archs = arm64-v8a

          [buildozer]
          log_level = 2
          EOF

      - name: Build APK
        env:
          BUILDOZER_WARN_ON_ROOT: 0
        run: buildozer android debug
